[package]
name = "noita_api"
version = "1.6.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
libloading = "0.8.5"
noita_api_macro = {path = "noita_api_macro"}
shared = {path = "../shared"}
base64 = "0.22.1"
rustc-hash = "2.0.0"
smallvec = "1.15.1"
object = "0.37.1"
rayon = "1.10.0"